version: '3.8'
services:
  db:
    container_name: postgresdb_container
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: users
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data
volumes:
  postgres: